// <auto-generated />
using System;
using ECS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECS.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260720133914_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECS.Domain.Entities.Auth.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_user_email")
                        .HasFilter("[email] IS NOT NULL");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasDatabaseName("ix_user_phone");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("ECS.Domain.Entities.Clinics.Clinic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<TimeOnly>("CloseTime")
                        .HasColumnType("time")
                        .HasColumnName("close_time");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPublicationRequested")
                        .HasColumnType("bit")
                        .HasColumnName("is_publication_requested");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit")
                        .HasColumnName("is_published");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<TimeOnly>("OpenTime")
                        .HasColumnType("time")
                        .HasColumnName("open_time");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.Property<DateTime?>("PublicationRequestedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("publication_requested_at");

                    b.Property<decimal?>("RatingAvg")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("rating_avg");

                    b.Property<int?>("ReviewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("review_count");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_clinic");

                    b.ToTable("clinic", (string)null);
                });

            modelBuilder.Entity("ECS.Domain.Entities.Clinics.ClinicRegistrationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("BusinessLicenseUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("business_license_url");

                    b.Property<string>("ClinicAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("clinic_address");

                    b.Property<string>("ClinicName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("clinic_name");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("contact_name");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("contact_phone");

                    b.Property<Guid?>("ProvisionedClinicId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("provisioned_clinic_id");

                    b.Property<DateTime>("RequestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("requested_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("review_note");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_clinic_registration_request");

                    b.HasIndex("ProvisionedClinicId")
                        .HasDatabaseName("ix_clinic_registration_request_provisioned_clinic_id");

                    b.HasIndex("ReviewedBy")
                        .HasDatabaseName("ix_clinic_registration_request_reviewed_by");

                    b.ToTable("clinic_registration_request", (string)null);
                });

            modelBuilder.Entity("ECS.Domain.Entities.Clinics.DoctorProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("bio");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("clinic_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("ExperienceYears")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("experience_years");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<decimal?>("RatingAvg")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("rating_avg");

                    b.Property<int?>("ReviewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("review_count");

                    b.Property<Guid?>("SpecialtyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("specialty_id");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_doctor_profile");

                    b.HasIndex("ClinicId")
                        .HasDatabaseName("ix_doctor_profile_clinic_id");

                    b.HasIndex("SpecialtyId")
                        .HasDatabaseName("ix_doctor_profile_specialty_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_doctor_profile_user_id");

                    b.ToTable("doctor_profile", (string)null);
                });

            modelBuilder.Entity("ECS.Domain.Entities.Clinics.FacilityRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("clinic_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("room_name");

                    b.Property<string>("RoomType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("room_type");

                    b.HasKey("Id")
                        .HasName("pk_facility_room");

                    b.HasIndex("ClinicId")
                        .HasDatabaseName("ix_facility_room_clinic_id");

                    b.ToTable("facility_room", (string)null);
                });

            modelBuilder.Entity("ECS.Domain.Entities.Clinics.MedicineCatalog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("clinic_id");

                    b.Property<string>("Concentration")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("concentration");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DosageForm")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("dosage_form");

                    b.Property<string>("GenericName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("generic_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("manufacturer");

                    b.Property<string>("MedicineName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("medicine_name");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("unit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_medicine_catalog");

                    b.HasIndex("ClinicId")
                        .HasDatabaseName("ix_medicine_catalog_clinic_id");

                    b.ToTable("medicine_catalog", (string)null);
                });

            modelBuilder.Entity("ECS.Domain.Entities.Clinics.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("clinic_id");

                    b.Property<int>("DurationMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(15)
                        .HasColumnName("duration_minutes");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("service_name");

                    b.HasKey("Id")
                        .HasName("pk_service");

                    b.HasIndex("ClinicId")
                        .HasDatabaseName("ix_service_clinic_id");

                    b.ToTable("service", (string)null);
                });

            modelBuilder.Entity("ECS.Domain.Entities.Clinics.Specialty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_specialty");

                    b.ToTable("specialty", (string)null);
                });

            modelBuilder.Entity("ECS.Domain.Entities.Clinics.StaffClinic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("clinic_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_staff_clinic");

                    b.HasIndex("ClinicId")
                        .HasDatabaseName("ix_staff_clinic_clinic_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_staff_clinic_user_id");

                    b.ToTable("staff_clinic", (string)null);
                });

            modelBuilder.Entity("ECS.Domain.Entities.Configurations.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("old_value");

                    b.Property<string>("RecordId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("record_id");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("table_name");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_log");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_audit_log_user_id");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("ECS.Domain.Entities.Configurations.PlatformConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ConfigKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("config_key");

                    b.Property<string>("ConfigValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("config_value");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_platform_config");

                    b.HasIndex("ConfigKey")
                        .IsUnique()
                        .HasDatabaseName("ix_platform_config_config_key");

                    b.ToTable("platform_config", (string)null);
                });

            modelBuilder.Entity("ECS.Domain.Entities.Feedbacks.Feedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("appointment_id");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("clinic_id");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("doctor_id");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_public");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("patient_id");

                    b.Property<int>("RatingClinic")
                        .HasColumnType("int")
                        .HasColumnName("rating_clinic");

                    b.Property<int>("RatingDoctor")
                        .HasColumnType("int")
                        .HasColumnName("rating_doctor");

                    b.HasKey("Id")
                        .HasName("pk_feedback");

                    b.HasIndex("AppointmentId")
                        .IsUnique()
                        .HasDatabaseName("ix_feedback_appointment_id");

                    b.HasIndex("ClinicId")
                        .HasDatabaseName("ix_feedback_clinic_id");

                    b.HasIndex("DoctorId")
                        .HasDatabaseName("ix_feedback_doctor_id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_feedback_patient_id");

                    b.ToTable("feedback", (string)null);
                });

            modelBuilder.Entity("ECS.Domain.Entities.MedicalRecords.DocumentAccessPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("GrantedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("granted_by_user_id");

                    b.Property<Guid>("GrantedToUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("granted_to_user_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<Guid>("MedicalRecordId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("medical_record_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_document_access_permission");

                    b.HasIndex("GrantedByUserId")
                        .HasDatabaseName("ix_document_access_permission_granted_by_user_id");

                    b.HasIndex("GrantedToUserId")
                        .HasDatabaseName("ix_document_access_permission_granted_to_user_id");

                    b.HasIndex("MedicalRecordId")
                        .HasDatabaseName("ix_document_access_permission_medical_record_id");

                    b.ToTable("document_access_permission", (string)null);
                });

            modelBuilder.Entity("ECS.Domain.Entities.MedicalRecords.EmrExportLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ExportFormat")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("export_format");

                    b.Property<Guid>("ExportedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("exported_by");

                    b.Property<string>("FileUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("file_url");

                    b.Property<Guid>("MedicalRecordId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("medical_record_id");

                    b.HasKey("Id")
                        .HasName("pk_emr_export_log");

                    b.HasIndex("ExportedBy")
                        .HasDatabaseName("ix_emr_export_log_exported_by");

                    b.HasIndex("MedicalRecordId")
                        .HasDatabaseName("ix_emr_export_log_medical_record_id");

                    b.ToTable("emr_export_log", (string)null);
                });

            modelBuilder.Entity("ECS.Domain.Entities.MedicalRecords.MedicalRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("appointment_id");

                    b.Property<string>("ChiefComplaint")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("chief_complaint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("doctor_id");

                    b.Property<DateTime?>("FinalizedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("finalized_at");

                    b.Property<Guid?>("FinalizedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("finalized_by");

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_locked");

                    b.Property<string>("MongoDocumentId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mongo_document_id");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("patient_id");

                    b.Property<string>("RecordDataChecksum")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("record_data_checksum");

                    b.Property<string>("RecordDataPublicId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("record_data_public_id");

                    b.Property<string>("RecordDataSchemaVersion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("1.0")
                        .HasColumnName("record_data_schema_version");

                    b.Property<long>("RecordDataSizeBytes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("record_data_size_bytes");

                    b.Property<string>("RecordDataUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("record_data_url");

                    b.Property<int>("RecordDataVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("record_data_version");

                    b.Property<string>("RecordType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("record_type");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("summary");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_medical_record");

                    b.HasIndex("AppointmentId")
                        .IsUnique()
                        .HasDatabaseName("ix_medical_record_appointment_id");

                    b.HasIndex("DoctorId")
                        .HasDatabaseName("ix_medical_record_doctor_id");

                    b.HasIndex("FinalizedBy")
                        .HasDatabaseName("ix_medical_record_finalized_by");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_medical_record_patient_id");

                    b.ToTable("medical_record", (string)null);
                });

            modelBuilder.Entity("ECS.Domain.Entities.MedicalRecords.PreliminaryDiagnosis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("appointment_id");

                    b.Property<DateTime?>("CheckInTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("check_in_time");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("doctor_id");

                    b.Property<string>("FollowUpInstructions")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("follow_up_instructions");

                    b.Property<bool>("HasEyeDischarge")
                        .HasColumnType("bit")
                        .HasColumnName("has_eye_discharge");

                    b.Property<bool>("HasEyePain")
                        .HasColumnType("bit")
                        .HasColumnName("has_eye_pain");

                    b.Property<bool>("HasEyeRedness")
                        .HasColumnType("bit")
                        .HasColumnName("has_eye_redness");

                    b.Property<bool>("HasForeignBody")
                        .HasColumnType("bit")
                        .HasColumnName("has_foreign_body");

                    b.Property<bool>("HasHeadache")
                        .HasColumnType("bit")
                        .HasColumnName("has_headache");

                    b.Property<bool>("HasLightSensitivity")
                        .HasColumnType("bit")
                        .HasColumnName("has_light_sensitivity");

                    b.Property<bool>("HasVisionChange")
                        .HasColumnType("bit")
                        .HasColumnName("has_vision_change");

                    b.Property<bool>("IsReferralNeeded")
                        .HasColumnType("bit")
                        .HasColumnName("is_referral_needed");

                    b.Property<int?>("PainLevel")
                        .HasColumnType("int")
                        .HasColumnName("pain_level");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("patient_id");

                    b.Property<string>("QuickVisualAssessment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("quick_visual_assessment");

                    b.Property<string>("RecommendedAction")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("recommended_action");

                    b.Property<string>("ReferralTo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("referral_to");

                    b.Property<DateTime?>("TriageCompletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("triage_completed_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int>("UrgencyLevel")
                        .HasColumnType("int")
                        .HasColumnName("urgency_level");

                    b.HasKey("Id")
                        .HasName("pk_preliminary_diagnoses");

                    b.HasIndex("AppointmentId")
                        .IsUnique()
                        .HasDatabaseName("ix_preliminary_diagnoses_appointment_id");

                    b.HasIndex("DoctorId")
                        .HasDatabaseName("ix_preliminary_diagnoses_doctor_id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_preliminary_diagnoses_patient_id");

                    b.ToTable("preliminary_diagnoses", (string)null);
                });

            modelBuilder.Entity("ECS.Domain.Entities.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("sent_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notification");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_notification_user_id");

                    b.ToTable("notification", (string)null);
                });

            modelBuilder.Entity("ECS.Domain.Entities.Paraclinical.OctResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal?>("CmtOd")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("cmt_od");

                    b.Property<decimal?>("CmtOs")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("cmt_os");

                    b.Property<string>("Conclusion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("conclusion");

                    b.Property<decimal?>("CupDiscRatioOd")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("cup_disc_ratio_od");

                    b.Property<decimal?>("CupDiscRatioOs")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("cup_disc_ratio_os");

                    b.Property<DateTime>("ExamDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("exam_date");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_url");

                    b.Property<string>("MachineName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("machine_name");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("record_id");

                    b.Property<decimal?>("RnflAverageOd")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("rnfl_average_od");

                    b.Property<decimal?>("RnflAverageOs")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("rnfl_average_os");

                    b.Property<string>("ScanPattern")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("scan_pattern");

                    b.Property<string>("TechnicianName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("technician_name");

                    b.HasKey("Id")
                        .HasName("pk_oct_result");

                    b.HasIndex("RecordId")
                        .HasDatabaseName("ix_oct_result_record_id");

                    b.ToTable("oct_result", (string)null);
                });

            modelBuilder.Entity("ECS.Domain.Entities.Paraclinical.UltrasoundEye", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal?>("AcDepthMm")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("ac_depth_mm");

                    b.Property<decimal?>("AxialLengthMm")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("axial_length_mm");

                    b.Property<string>("Conclusion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("conclusion");

                    b.Property<DateTime>("ExamDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("exam_date");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_url");

                    b.Property<string>("LensStatus")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("lens_status");

                    b.Property<decimal?>("LensThicknessMm")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("lens_thickness_mm");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("record_id");

                    b.Property<string>("RetinaStatus")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("retina_status");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("side");

                    b.Property<string>("TechnicianName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("technician_name");

                    b.Property<string>("UltrasoundType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ultrasound_type");

                    b.Property<decimal?>("VitreousLengthMm")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("vitreous_length_mm");

                    b.HasKey("Id")
                        .HasName("pk_ultrasound_eye");

                    b.HasIndex("RecordId")
                        .HasDatabaseName("ix_ultrasound_eye_record_id");

                    b.ToTable("ultrasound_eye", (string)null);
                });

            modelBuilder.Entity("ECS.Domain.Entities.Paraclinical.VisualFieldTest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_url");

                    b.Property<string>("Machine")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("machine");

                    b.Property<decimal?>("MdValue")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("md_value");

                    b.Property<decimal?>("PsdValue")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("psd_value");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("record_id");

                    b.Property<bool>("Reliable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("reliable");

                    b.Property<string>("ResultSummary")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("result_summary");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("side");

                    b.Property<string>("Strategy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("strategy");

                    b.Property<string>("TechnicianName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("technician_name");

                    b.Property<DateTime>("TestDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("test_date");

                    b.Property<decimal?>("VfiPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("vfi_percent");

                    b.HasKey("Id")
                        .HasName("pk_visual_field_test");

                    b.HasIndex("RecordId")
                        .HasDatabaseName("ix_visual_field_test_record_id");

                    b.ToTable("visual_field_test", (string)null);
                });

            modelBuilder.Entity("ECS.Domain.Entities.Patient.PatientProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<string>("Allergies")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("allergies");

                    b.Property<string>("BhytNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("bhyt_number");

                    b.Property<string>("BloodType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("blood_type");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CurrentEyeMedications")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("current_eye_medications");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("dob");

                    b.Property<string>("EyeVisionHistory")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("eye_vision_history");

                    b.Property<string>("FamilyHistory")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("family_history");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("gender");

                    b.Property<bool>("HasMedicalDemographics")
                        .HasColumnType("bit")
                        .HasColumnName("has_medical_demographics");

                    b.Property<string>("IdentityNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("identity_number");

                    b.Property<string>("LifestyleFactors")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lifestyle_factors");

                    b.Property<string>("MedicalHistory")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("medical_history");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("PreviousEyeSurgery")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("previous_eye_surgery");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_patient_profile");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_patient_profile_user_id");

                    b.ToTable("patient_profile", (string)null);
                });

            modelBuilder.Entity("ECS.Domain.Entities.Patient.UserPatient", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("patient_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Relationship")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("relationship");

                    b.HasKey("UserId", "PatientId")
                        .HasName("pk_user_patient");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_user_patient_patient_id");

                    b.ToTable("user_patient", (string)null);
                });

            modelBuilder.Entity("ECS.Domain.Entities.Scheduling.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("appointment_date");

                    b.Property<string>("BookingSource")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("ONLINE")
                        .HasColumnName("booking_source");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by_id");

                    b.Property<decimal>("DepositAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("deposit_amount");

                    b.Property<bool>("DepositPaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("deposit_paid");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("doctor_id");

                    b.Property<Guid?>("FollowUpFromAppointmentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("follow_up_from_appointment_id");

                    b.Property<string>("NoteReason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note_reason");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("patient_id");

                    b.Property<Guid?>("ServiceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("service_id");

                    b.Property<Guid>("SlotId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("slot_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("status");

                    b.Property<string>("Symptoms")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("symptoms");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_appointment");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_appointment_created_by_id");

                    b.HasIndex("DoctorId")
                        .HasDatabaseName("ix_appointment_doctor_id");

                    b.HasIndex("FollowUpFromAppointmentId")
                        .HasDatabaseName("ix_appointment_follow_up_from_appointment_id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_appointment_patient_id");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_appointment_service_id");

                    b.HasIndex("SlotId")
                        .HasDatabaseName("ix_appointment_slot_id");

                    b.ToTable("appointment", (string)null);
                });

            modelBuilder.Entity("ECS.Domain.Entities.Scheduling.DoctorSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("doctor_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("room_id");

                    b.Property<string>("ShiftType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("shift_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("date")
                        .HasColumnName("work_date");

                    b.HasKey("Id")
                        .HasName("pk_doctor_schedule");

                    b.HasIndex("DoctorId")
                        .HasDatabaseName("ix_doctor_schedule_doctor_id");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("ix_doctor_schedule_room_id");

                    b.ToTable("doctor_schedule", (string)null);
                });

            modelBuilder.Entity("ECS.Domain.Entities.Scheduling.Queue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("appointment_id");

                    b.Property<DateTime?>("CalledAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("called_at");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("clinic_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("QueueNumber")
                        .HasColumnType("int")
                        .HasColumnName("queue_number");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("room_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("WAITING")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_queue");

                    b.HasIndex("AppointmentId")
                        .IsUnique()
                        .HasDatabaseName("ix_queue_appointment_id");

                    b.HasIndex("ClinicId")
                        .HasDatabaseName("ix_queue_clinic_id");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("ix_queue_room_id");

                    b.ToTable("queue", (string)null);
                });

            modelBuilder.Entity("ECS.Domain.Entities.Scheduling.TimeSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("CurrentPatients")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("current_patients");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_time");

                    b.Property<int>("MaxPatients")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("max_patients");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("schedule_id");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("AVAILABLE")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_time_slot");

                    b.HasIndex("ScheduleId")
                        .HasDatabaseName("ix_time_slot_schedule_id");

                    b.ToTable("time_slot", (string)null);
                });

            modelBuilder.Entity("ECS.Domain.Entities.Clinics.ClinicRegistrationRequest", b =>
                {
                    b.HasOne("ECS.Domain.Entities.Clinics.Clinic", "ProvisionedClinic")
                        .WithMany()
                        .HasForeignKey("ProvisionedClinicId")
                        .HasConstraintName("fk_clinic_registration_request_clinic_provisioned_clinic_id");

                    b.HasOne("ECS.Domain.Entities.Auth.User", "Reviewer")
                        .WithMany("ReviewedRequests")
                        .HasForeignKey("ReviewedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_clinic_registration_request_users_reviewed_by");

                    b.Navigation("ProvisionedClinic");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("ECS.Domain.Entities.Clinics.DoctorProfile", b =>
                {
                    b.HasOne("ECS.Domain.Entities.Clinics.Clinic", "Clinic")
                        .WithMany("DoctorProfiles")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_doctor_profile_clinic_clinic_id");

                    b.HasOne("ECS.Domain.Entities.Clinics.Specialty", "Specialty")
                        .WithMany("DoctorProfiles")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_doctor_profile_specialties_specialty_id");

                    b.HasOne("ECS.Domain.Entities.Auth.User", "User")
                        .WithMany("DoctorProfiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_doctor_profile_users_user_id");

                    b.Navigation("Clinic");

                    b.Navigation("Specialty");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECS.Domain.Entities.Clinics.FacilityRoom", b =>
                {
                    b.HasOne("ECS.Domain.Entities.Clinics.Clinic", "Clinic")
                        .WithMany("FacilityRooms")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_facility_room_clinic_clinic_id");

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("ECS.Domain.Entities.Clinics.MedicineCatalog", b =>
                {
                    b.HasOne("ECS.Domain.Entities.Clinics.Clinic", "Clinic")
                        .WithMany("MedicineCatalogs")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_medicine_catalog_clinic_clinic_id");

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("ECS.Domain.Entities.Clinics.Service", b =>
                {
                    b.HasOne("ECS.Domain.Entities.Clinics.Clinic", "Clinic")
                        .WithMany("Services")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_clinic_clinic_id");

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("ECS.Domain.Entities.Clinics.StaffClinic", b =>
                {
                    b.HasOne("ECS.Domain.Entities.Clinics.Clinic", "Clinic")
                        .WithMany("StaffClinics")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_staff_clinic_clinic_clinic_id");

                    b.HasOne("ECS.Domain.Entities.Auth.User", "User")
                        .WithMany("StaffClinics")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_staff_clinic_users_user_id");

                    b.Navigation("Clinic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECS.Domain.Entities.Configurations.AuditLog", b =>
                {
                    b.HasOne("ECS.Domain.Entities.Auth.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_audit_log_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECS.Domain.Entities.Feedbacks.Feedback", b =>
                {
                    b.HasOne("ECS.Domain.Entities.Scheduling.Appointment", "Appointment")
                        .WithOne("Feedback")
                        .HasForeignKey("ECS.Domain.Entities.Feedbacks.Feedback", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_feedback_appointment_appointment_id");

                    b.HasOne("ECS.Domain.Entities.Clinics.Clinic", "Clinic")
                        .WithMany("Feedbacks")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_feedback_clinic_clinic_id");

                    b.HasOne("ECS.Domain.Entities.Clinics.DoctorProfile", "Doctor")
                        .WithMany("Feedbacks")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_feedback_doctor_profile_doctor_id");

                    b.HasOne("ECS.Domain.Entities.Patient.PatientProfile", "Patient")
                        .WithMany("Feedbacks")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_feedback_patient_profiles_patient_id");

                    b.Navigation("Appointment");

                    b.Navigation("Clinic");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ECS.Domain.Entities.MedicalRecords.DocumentAccessPermission", b =>
                {
                    b.HasOne("ECS.Domain.Entities.Auth.User", "GrantedByUser")
                        .WithMany("GrantedByPermissions")
                        .HasForeignKey("GrantedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_document_access_permission_users_granted_by_user_id");

                    b.HasOne("ECS.Domain.Entities.Auth.User", "GrantedToUser")
                        .WithMany("GrantedPermissions")
                        .HasForeignKey("GrantedToUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_document_access_permission_users_granted_to_user_id");

                    b.HasOne("ECS.Domain.Entities.MedicalRecords.MedicalRecord", "MedicalRecord")
                        .WithMany("DocumentAccessPermissions")
                        .HasForeignKey("MedicalRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_document_access_permission_medical_records_medical_record_id");

                    b.Navigation("GrantedByUser");

                    b.Navigation("GrantedToUser");

                    b.Navigation("MedicalRecord");
                });

            modelBuilder.Entity("ECS.Domain.Entities.MedicalRecords.EmrExportLog", b =>
                {
                    b.HasOne("ECS.Domain.Entities.Auth.User", "Exporter")
                        .WithMany("EmrExportLogs")
                        .HasForeignKey("ExportedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_emr_export_log_users_exported_by");

                    b.HasOne("ECS.Domain.Entities.MedicalRecords.MedicalRecord", "MedicalRecord")
                        .WithMany("EmrExportLogs")
                        .HasForeignKey("MedicalRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_emr_export_log_medical_records_medical_record_id");

                    b.Navigation("Exporter");

                    b.Navigation("MedicalRecord");
                });

            modelBuilder.Entity("ECS.Domain.Entities.MedicalRecords.MedicalRecord", b =>
                {
                    b.HasOne("ECS.Domain.Entities.Scheduling.Appointment", "Appointment")
                        .WithOne("MedicalRecord")
                        .HasForeignKey("ECS.Domain.Entities.MedicalRecords.MedicalRecord", "AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_medical_record_appointment_appointment_id");

                    b.HasOne("ECS.Domain.Entities.Clinics.DoctorProfile", "Doctor")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_medical_record_doctor_profile_doctor_id");

                    b.HasOne("ECS.Domain.Entities.Auth.User", "FinalizedByUser")
                        .WithMany()
                        .HasForeignKey("FinalizedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_medical_record_users_finalized_by");

                    b.HasOne("ECS.Domain.Entities.Patient.PatientProfile", "Patient")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_medical_record_patient_profiles_patient_id");

                    b.Navigation("Appointment");

                    b.Navigation("Doctor");

                    b.Navigation("FinalizedByUser");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ECS.Domain.Entities.MedicalRecords.PreliminaryDiagnosis", b =>
                {
                    b.HasOne("ECS.Domain.Entities.Scheduling.Appointment", "Appointment")
                        .WithOne("PreliminaryDiagnosis")
                        .HasForeignKey("ECS.Domain.Entities.MedicalRecords.PreliminaryDiagnosis", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_preliminary_diagnoses_appointments_appointment_id");

                    b.HasOne("ECS.Domain.Entities.Clinics.DoctorProfile", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_preliminary_diagnoses_doctor_profiles_doctor_id");

                    b.HasOne("ECS.Domain.Entities.Patient.PatientProfile", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_preliminary_diagnoses_patient_profiles_patient_id");

                    b.Navigation("Appointment");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ECS.Domain.Entities.Notifications.Notification", b =>
                {
                    b.HasOne("ECS.Domain.Entities.Auth.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notification_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECS.Domain.Entities.Paraclinical.OctResult", b =>
                {
                    b.HasOne("ECS.Domain.Entities.MedicalRecords.MedicalRecord", "MedicalRecord")
                        .WithMany()
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_oct_result_medical_record_record_id");

                    b.Navigation("MedicalRecord");
                });

            modelBuilder.Entity("ECS.Domain.Entities.Paraclinical.UltrasoundEye", b =>
                {
                    b.HasOne("ECS.Domain.Entities.MedicalRecords.MedicalRecord", "MedicalRecord")
                        .WithMany()
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ultrasound_eye_medical_record_record_id");

                    b.Navigation("MedicalRecord");
                });

            modelBuilder.Entity("ECS.Domain.Entities.Paraclinical.VisualFieldTest", b =>
                {
                    b.HasOne("ECS.Domain.Entities.MedicalRecords.MedicalRecord", "MedicalRecord")
                        .WithMany()
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_visual_field_test_medical_record_record_id");

                    b.Navigation("MedicalRecord");
                });

            modelBuilder.Entity("ECS.Domain.Entities.Patient.PatientProfile", b =>
                {
                    b.HasOne("ECS.Domain.Entities.Auth.User", "User")
                        .WithMany("PatientProfiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_patient_profile_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECS.Domain.Entities.Patient.UserPatient", b =>
                {
                    b.HasOne("ECS.Domain.Entities.Patient.PatientProfile", "Patient")
                        .WithMany("UserPatients")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_patient_patient_profile_patient_id");

                    b.HasOne("ECS.Domain.Entities.Auth.User", "User")
                        .WithMany("UserPatients")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_patient_user_user_id");

                    b.Navigation("Patient");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECS.Domain.Entities.Scheduling.Appointment", b =>
                {
                    b.HasOne("ECS.Domain.Entities.Auth.User", "CreatedBy")
                        .WithMany("AppointmentsCreated")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_appointment_users_created_by_id");

                    b.HasOne("ECS.Domain.Entities.Clinics.DoctorProfile", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_appointment_doctor_profiles_doctor_id");

                    b.HasOne("ECS.Domain.Entities.Scheduling.Appointment", "FollowUpFrom")
                        .WithMany("FollowUpAppointments")
                        .HasForeignKey("FollowUpFromAppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_appointment_appointment_follow_up_from_appointment_id");

                    b.HasOne("ECS.Domain.Entities.Patient.PatientProfile", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_appointment_patient_profiles_patient_id");

                    b.HasOne("ECS.Domain.Entities.Clinics.Service", "Service")
                        .WithMany("Appointments")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_appointment_services_service_id");

                    b.HasOne("ECS.Domain.Entities.Scheduling.TimeSlot", "Slot")
                        .WithMany("Appointments")
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_appointment_time_slots_slot_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("Doctor");

                    b.Navigation("FollowUpFrom");

                    b.Navigation("Patient");

                    b.Navigation("Service");

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("ECS.Domain.Entities.Scheduling.DoctorSchedule", b =>
                {
                    b.HasOne("ECS.Domain.Entities.Clinics.DoctorProfile", "Doctor")
                        .WithMany("DoctorSchedules")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_doctor_schedule_doctor_profile_doctor_id");

                    b.HasOne("ECS.Domain.Entities.Clinics.FacilityRoom", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .HasConstraintName("fk_doctor_schedule_facility_rooms_room_id");

                    b.Navigation("Doctor");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("ECS.Domain.Entities.Scheduling.Queue", b =>
                {
                    b.HasOne("ECS.Domain.Entities.Scheduling.Appointment", "Appointment")
                        .WithOne("Queue")
                        .HasForeignKey("ECS.Domain.Entities.Scheduling.Queue", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_queue_appointment_appointment_id");

                    b.HasOne("ECS.Domain.Entities.Clinics.Clinic", "Clinic")
                        .WithMany("Queues")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_queue_clinic_clinic_id");

                    b.HasOne("ECS.Domain.Entities.Clinics.FacilityRoom", "Room")
                        .WithMany("Queues")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_queue_facility_room_room_id");

                    b.Navigation("Appointment");

                    b.Navigation("Clinic");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("ECS.Domain.Entities.Scheduling.TimeSlot", b =>
                {
                    b.HasOne("ECS.Domain.Entities.Scheduling.DoctorSchedule", "Schedule")
                        .WithMany("TimeSlots")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_time_slot_doctor_schedule_schedule_id");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("ECS.Domain.Entities.Auth.User", b =>
                {
                    b.Navigation("AppointmentsCreated");

                    b.Navigation("AuditLogs");

                    b.Navigation("DoctorProfiles");

                    b.Navigation("EmrExportLogs");

                    b.Navigation("GrantedByPermissions");

                    b.Navigation("GrantedPermissions");

                    b.Navigation("Notifications");

                    b.Navigation("PatientProfiles");

                    b.Navigation("ReviewedRequests");

                    b.Navigation("StaffClinics");

                    b.Navigation("UserPatients");
                });

            modelBuilder.Entity("ECS.Domain.Entities.Clinics.Clinic", b =>
                {
                    b.Navigation("DoctorProfiles");

                    b.Navigation("FacilityRooms");

                    b.Navigation("Feedbacks");

                    b.Navigation("MedicineCatalogs");

                    b.Navigation("Queues");

                    b.Navigation("Services");

                    b.Navigation("StaffClinics");
                });

            modelBuilder.Entity("ECS.Domain.Entities.Clinics.DoctorProfile", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("DoctorSchedules");

                    b.Navigation("Feedbacks");

                    b.Navigation("MedicalRecords");
                });

            modelBuilder.Entity("ECS.Domain.Entities.Clinics.FacilityRoom", b =>
                {
                    b.Navigation("Queues");
                });

            modelBuilder.Entity("ECS.Domain.Entities.Clinics.Service", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("ECS.Domain.Entities.Clinics.Specialty", b =>
                {
                    b.Navigation("DoctorProfiles");
                });

            modelBuilder.Entity("ECS.Domain.Entities.MedicalRecords.MedicalRecord", b =>
                {
                    b.Navigation("DocumentAccessPermissions");

                    b.Navigation("EmrExportLogs");
                });

            modelBuilder.Entity("ECS.Domain.Entities.Patient.PatientProfile", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Feedbacks");

                    b.Navigation("MedicalRecords");

                    b.Navigation("UserPatients");
                });

            modelBuilder.Entity("ECS.Domain.Entities.Scheduling.Appointment", b =>
                {
                    b.Navigation("Feedback");

                    b.Navigation("FollowUpAppointments");

                    b.Navigation("MedicalRecord");

                    b.Navigation("PreliminaryDiagnosis");

                    b.Navigation("Queue");
                });

            modelBuilder.Entity("ECS.Domain.Entities.Scheduling.DoctorSchedule", b =>
                {
                    b.Navigation("TimeSlots");
                });

            modelBuilder.Entity("ECS.Domain.Entities.Scheduling.TimeSlot", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
